description = "Webcard (Short Profile) for Angel Crawford. Developer. Sun lover. Goth."
keywords = "Webcard, Profile Card, Angel Crawford"
shareImage = "images/social.en.jpg"
favicon = "favicon.en.ico"
flag_file = "images/en.en.png"
flag_title = "Change the Language to"
spotifyPlaylist = "https://open.spotify.com/embed/playlist/520act29dQq3SDNilMbpfd"
birthdate = "1987-02-05"

[visual.image]
  enable = true
  size = "cover"
  position = "center top"
  count = 6 # Anzahl der Bilder im Slider
  speed = "1s" # Sekunden die der Slider zum Wechsel benÃ¶tigt

  [[visual.image.file]]
    url = "images/slider/background_1_2000px.en.jpg"
    url_smallish = "images/slider/background_1_1200px.en.jpg"
    url_tablet = "images/slider/background_1_800px.en.jpg"
    url_mobile = "images/slider/background_1_500px.en.jpg"
    credit = "ðŸ“… 2015-01-11 <small>|</small> ðŸ“· <a href='https://www.facebook.com/lichtundschattenspiel'>Licht- und Schattenspiel</a> <small>|</small> ðŸ’„ <a href='https://www.facebook.com/KaraKuckoo'>Kara Kuckoo</a>"

  [[visual.image.file]]
    url = "images/slider/background_2_2000px.en.jpg"
    url_smallish = "images/slider/background_2_1200px.en.jpg"
    url_tablet = "images/slider/background_2_800px.en.jpg"
    url_mobile = "images/slider/background_2_500px.en.jpg"
    credit = "ðŸ“… 2013-05-14 <small>|</small> ðŸ“· <a href='https://www.facebook.com/lichtundschattenspiel'>Licht- und Schattenspiel</a> <small>|</small> ðŸ’„ Me"

  [[visual.image.file]]
    url = "images/slider/background_3_2000px.en.jpg"
    url_smallish = "images/slider/background_3_1200px.en.jpg"
    url_tablet = "images/slider/background_3_800px.en.jpg"
    url_mobile = "images/slider/background_3_500px.en.jpg"
    credit = "ðŸ“… 2015-01-11 <small>|</small> ðŸ“· <a href='https://www.facebook.com/lichtundschattenspiel'>Licht- und Schattenspiel</a> <small>|</small> ðŸ’„ <a href='https://www.facebook.com/KaraKuckoo'>Kara Kuckoo</a>"

  [[visual.image.file]]
    url = "images/slider/background_6_2000px.en.jpg"
    url_smallish = "images/slider/background_6_1200px.en.jpg"
    url_tablet = "images/slider/background_6_800px.en.jpg"
    url_mobile = "images/slider/background_6_500px.en.jpg"
    credit = "ðŸ“… 2020-08-01 <small>|</small> ðŸ“· <a href='https://www.facebook.com/BrainfoodPhotographyDesign'>Brainfood Photography & Layout</a> <small>|</small> ðŸ’„ Costume by me ;)"

  [[visual.image.file]]
    url = "images/slider/background_4.en.jpg"
    credit = "ðŸ“… 2019-09-28 <small>|</small> ðŸ“· Me <small>|</small> ðŸ’„ Me"

  [[visual.image.file]]
    url = "images/slider/background_7.en.png"
    credit = "ðŸ“… 2021-02-06 <small>|</small> ðŸ“· Me <small>|</small> ðŸ’„ Me"


[visual.video]
  enable = false
  mute = true
  file = "videos/background.mp4"
  #youtubeId = "dk9uNWPP7EA"


[list_type]
  icons = true
  round_icons = false
  hover_color = false


[[links]]
  [links.list1]
    heading = "Connect"
    # [[languages.en.params.links.list1.link]]
    #   text = "Blog"
    #   url = "#"
    #   icon = "fas fa-link"

  [links.list2]
    heading = "Social"
    [[links.list2.link]]
      text = "Instagram"
      url = "https://www.instagram.com/angel_crawford_ftw"
      icon = "fab fa-instagram"
      color = "#c13584"
    [[links.list2.link]]
      text = "Facebook"
      url = "https://www.facebook.com/angel.crawford.ftw"
      icon = "fab fa-facebook"
      color = "#4267B2"
    [[links.list2.link]]
      text = "Twitter"
      url = "https://twitter.com/crawford_ftw"
      icon = "fab fa-twitter"
      color = "#1da1f2"
      opacity = "0.8"
    [[links.list2.link]]
      text = "TikTok"
      url = "https://www.tiktok.com/@angel_crawford_ftw"
      icon = "fab fa-tiktok"
      color = "#EE1D52"
      opacity = "0.7"
    [[links.list2.link]]
      text = "Twitch"
      url = "https://www.twitch.tv/angel_crawford"
      icon = "fab fa-twitch"
      color = "#6441a5"
    [[links.list2.link]]
      text = "Spotify"
      url = "https://open.spotify.com/user/l73ksvrl7vnidevukda1z0kwj"
      icon = "fab fa-spotify"
      color = "#1DB954"
      opacity = "0.8"

  [links.list3]
    heading = "Develop"
    [[links.list3.link]]
      text = "Github"
      url = "https://github.com/AngelCrawford"
      icon = "fab fa-github"
      color = "#555"
    [[links.list3.link]]
      text = "CodePen"
      url = "https://codepen.io/angel_crawford"
      icon = "fab fa-codepen"
      color = "#888"
    [[links.list3.link]]
      text = "Stack Overflow"
      url = "https://stackoverflow.com/u/3206211"
      icon = "fab fa-stack-overflow"
      color= "#f48024"
      opacity = "0.8"
